#!/bin/sh
DBNAME=$1
: ${DBNAME:=sugarult}
export DB2DBDFT=$DBNAME
db2 "FORCE APPLICATION ALL"
db2stop
db2start
db2 "FORCE APPLICATION ALL"
db2 "DROP DATABASE $DBNAME" 
db2 "CREATE DATABASE $DBNAME USING CODESET UTF-8 TERRITORY US COLLATE USING UCA500R1_LEN_S2 PAGESIZE 32 K"
db2 "CONNECT TO $DBNAME"
db2 "UPDATE database configuration for $DBNAME using DATABASE_MEMORY AUTOMATIC"
db2 "UPDATE database configuration for $DBNAME using logfilsiz 2048"
db2set DB2_COMPATIBILITY_VECTOR=4008
db2 "CREATE BUFFERPOOL SUGARBP IMMEDIATE SIZE 1000 AUTOMATIC PAGESIZE 32 K"
db2 "CREATE LARGE TABLESPACE SUGARTS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 32 OVERHEAD 10.5 PREFETCHSIZE 32 TRANSFERRATE 0.14 BUFFERPOOL SUGARBP"
db2 "CREATE USER TEMPORARY TABLESPACE SUGARXGTTTS IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 32 PREFETCHSIZE 32 BUFFERPOOL SUGARBP OVERHEAD 7.5 TRANSFERRATE 0.06 NO FILE SYSTEM CACHING"
db2 "FORCE APPLICATION ALL"
db2stop
db2start
db2 "CONNECT TO $DBNAME"
